//import { Inter } from 'next/font/google'
import { Poppins } from "next/font/google";
import './globals.css'
import Menu from './Menu';
import Footer from './Footer';

//const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/*<body className={inter.className}>{children}</body>*/}
      <body className={poppins.className}>
        <div>
          <div><Menu/></div>
          <div className="ml-3">{children}</div>
          <div className="ml-3 mr-3"><Footer/></div>
        </div>
      </body>
    </html>
  )
}
